### ISSUE TITLE
Can't define methods

### ISSUE THREAD

**Issue by willfaught** [x-motemen/gore#34] opened 2015-07-14 00:07 UTC
```
$ gore
gore version 0.2.2  :help for help
gore> type X struct {}
gore> func (X) Y() {}
..... 
..... 
..... 
```

**Comment by motemen** [comment] 2015-07-14 01:22
Thanks, currently gore does not support top-level definitions as it injects code inside `main()`. Marked as a feature request and I'm gonna try it later.

**Comment by willfaught** [comment] 2015-07-14 22:24
OK, thanks. Even a message saying it's not supported would be fine; it seems like I hit a bug otherwise.

**Comment by motemen** [comment] 2015-07-15 07:10
Ah, agreed. Current behavior must be confusing.

**Comment by Lenskiy** [comment] 2016-10-09 11:23
Would it be possible to search for the keyword **func** and if it is, copy whatever follows, to right before the main func ?

**Comment by itchyny** [comment] 2019-02-20 14:02
The issue is resolved now.

**Comment by xiantang** [comment] 2021-12-11 06:51
![image](https://user-images.githubusercontent.com/34479567/145667418-c19c901c-7192-4341-a23b-a43ba3db0447.png)
still not support struct method in 0.5.3

**Comment by itchyny** [comment] 2022-05-06 08:43
Reopening as the original issue is not still resolved in 0.5.3.

**Closed** 2022-05-06 09:08 UTC
Labels: func

**Comment by itchyny** [comment] 2022-05-06 13:10
This has been resolved in v0.5.5.

**Comment by willfaught** [comment] 2022-06-11 22:55
@motemen @itchyny Thank you! 🙏
